# Generated by Django 3.1.2 on 2020-10-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Lasshow',
            field=models.IntegerField(default=0),
        ),
    ]
