# Generated by Django 3.1.2 on 2020-10-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=400)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=400)),
                ('artID', models.CharField(max_length=15)),
                ('catid', models.IntegerField(default=0)),
                ('discripton', models.TextField(default='discription')),
                ('artbody', models.TextField(default='discription')),
                ('pic', models.ImageField(blank=True, default='art.png', null=True, upload_to='Article')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=50)),
                ('show', models.IntegerField(default=0)),
                ('tag', models.TextField(default='')),
                ('act', models.IntegerField(default=0)),
                ('rand', models.IntegerField(default=0)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.cat')),
            ],
        ),
    ]
