# Generated by Django 3.1.2 on 2020-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='show',
            field=models.IntegerField(default=0),
        ),
    ]
