# Generated by Django 3.1.2 on 2020-10-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_cat_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.CharField(default='cat', max_length=400),
        ),
    ]
