# Generated by Django 3.1.2 on 2020-10-13 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=400)),
                ('artId', models.CharField(default='artId', max_length=400)),
                ('Artname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='article.article')),
            ],
        ),
    ]
